version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0  
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package 
      - run:
          name: Unit Tests
          command: mvn test  
      

workflows:
  version: 2
  master-branch-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master

orbs:
  codecov: codecov/codecov@4.0.1
workflows:
  upload-to-codecov:
    jobs:
      - checkout 
      - codecov/upload