version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0  
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package 
      - run:
          name: Unit Tests
          command: mvn test  
      - run:
          name: Checkstyle
          command: mvn checkstyle:check  
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      
      - run:
          name: Générer les Javadocs
          command: mvn javadoc:javadoc
      - run:
        name: Debug Javadoc Directory
        command: ls -la target/
      - run:
          name: Déployer les Javadocs sur GitHub Pages
          command: |
            git config --global user.name "circleci"
            git config --global user.email "circleci@example.com"
            git clone --branch gh-pages https://$GITHUB_TOKEN@github.com/AxLaiR/ceri-m1-techniques-de-test.git gh-pages
            rm -rf gh-pages/*
            cp -r target/site/apidocs/* gh-pages/
            cd gh-pages
            git add .
            git commit -m "Javadocs générées par CircleCI"
            git push origin gh-pages
      
      

workflows:
  version: 2
  master-branch-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master