version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0  
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package 
      - run:
          name: Unit Tests
          command: mvn test  
      - run:
          name: Checkstyle
          command: mvn checkstyle:check  
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
      
      

workflows:
  version: 2
  master-branch-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master